FROM ros:jazzy

# 1. Aggiornamento sistema, strumenti base e compilatori per Python
# Nota: aggiunto 'python3-numpy' per risolvere l'errore di build di rosidl_generator_py
RUN apt update -y && apt install -y wget git nano curl python3-dev build-essential libgl1 libglib2.0-0 python3-numpy

# 2. Strumenti grafici di debug per ROS 2
# Nota: aggiunto rviz2 per la visualizzazione delle costmap e dei robot
RUN apt update -y && apt install -y ros-jazzy-rqt-graph ros-jazzy-rqt-tf-tree ros-jazzy-rviz2

# 3. AMBIENTE E ROBOT: Gazebo Harmonic e URDF/Xacro
RUN apt-get update -y && apt-get install -y ros-jazzy-ros-gz ros-jazzy-xacro ros-jazzy-turtlebot4-description ros-jazzy-irobot-create-* && rm -rf /var/lib/apt/lists/*

# 3.5. MAPPATURA: SLAM Toolbox
RUN apt update -y && apt install -y ros-jazzy-slam-toolbox ros-jazzy-teleop-twist-keyboard

# 4. NAVIGAZIONE: Nav2 Stack
RUN apt update -y && apt install -y ros-jazzy-navigation2 ros-jazzy-nav2-bringup

# 5. LOCALIZZAZIONE E SENSORI: EKF e AprilTags
RUN apt update -y && apt install -y ros-jazzy-robot-localization ros-jazzy-apriltag-ros

# 6. VISIONE ARTIFICIALE: OpenCV e ROS2
RUN apt update -y && apt install -y ros-jazzy-vision-opencv

# 7. INSTALLAZIONE 'uv' (Sostituto ottimizzato di pip --- visto dal c3lab del prof. Brescia ---)
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"

# 8. YOLOv8 tramite Virtual Environment gestito da uv
# Creiamo l'ambiente virtuale con ACCESSO ALLE LIBRERIE DI SISTEMA (ROS 2)
RUN uv venv --system-site-packages /opt/venv

# Attiviamo l'ambiente SOLO per questa istruzione e installiamo YOLO e NumPy
RUN . /opt/venv/bin/activate && uv pip install "numpy<2.0.0" ultralytics