# FROM ros:jazzy

# # 1. Aggiornamento sistema, strumenti base e compilatori per Python
# RUN apt update -y && apt install -y wget git nano python3-pip python3-dev build-essential libgl1 libglib2.0-0

# # 2. Strumenti grafici di debug per ROS 2
# RUN apt update -y && apt install -y ros-jazzy-rqt-graph ros-jazzy-rqt-tf-tree

# # 3. AMBIENTE E ROBOT: Gazebo Harmonic e URDF/Xacro
# RUN apt update -y && apt install -y ros-jazzy-ros-gz ros-jazzy-xacro

# # 4. NAVIGAZIONE: Nav2 Stack
# RUN apt update -y && apt install -y ros-jazzy-navigation2 ros-jazzy-nav2-bringup

# # 5. LOCALIZZAZIONE E SENSORI: EKF e AprilTags
# RUN apt update -y && apt install -y ros-jazzy-robot-localization ros-jazzy-apriltag-ros

# # 6. VISIONE ARTIFICIALE: OpenCV e ROS2
# RUN apt update -y && apt install -y ros-jazzy-vision-opencv

# # 7. YOLOv8 tramite Virtual Environment
# RUN pip install --upgrade pip setuptools wheel
# RUN pip install ultralytics

FROM ros:jazzy

# 1. Aggiornamento sistema, strumenti base e compilatori per Python
# Nota: aggiunto 'curl' che è necessario per scaricare 'uv'
RUN apt update -y && apt install -y wget git nano curl python3-dev build-essential libgl1 libglib2.0-0

# 2. Strumenti grafici di debug per ROS 2
# Nota: aggiunto rviz2 per la visualizzazione delle costmap e dei robot
RUN apt update -y && apt install -y ros-jazzy-rqt-graph ros-jazzy-rqt-tf-tree ros-jazzy-rviz2

# 3. AMBIENTE E ROBOT: Gazebo Harmonic e URDF/Xacro
RUN apt update -y && apt install -y ros-jazzy-ros-gz ros-jazzy-xacro

# 4. NAVIGAZIONE: Nav2 Stack
RUN apt update -y && apt install -y ros-jazzy-navigation2 ros-jazzy-nav2-bringup

# 5. LOCALIZZAZIONE E SENSORI: EKF e AprilTags
RUN apt update -y && apt install -y ros-jazzy-robot-localization ros-jazzy-apriltag-ros

# 6. VISIONE ARTIFICIALE: OpenCV e ROS2
RUN apt update -y && apt install -y ros-jazzy-vision-opencv

# 7. INSTALLAZIONE 'uv' (Sostituto ottimizzato di pip --- visto dal c3lab del prof. Brescia ---)
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"

# 8. YOLOv8 tramite Virtual Environment gestito da uv
# Creiamo l'ambiente virtuale, lo attiviamo e installiamo la rete neurale in modo sicuro
RUN uv venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN uv pip install ultralytics