<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>security_fleet_description</name>
  <version>1.0.0</version>
  <description>TurtleBot 4 modificato con telecamera rotante a 360 gradi</description>
  <maintainer email="studente@uniba.it">Studente</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <depend>turtlebot4_description</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>